version: '3.9'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - myNetwork


  serv:
    build: .
    ports:
      - '8080:8080'
    networks:
      - myNetwork
    depends_on:
      - db


networks:
  myNetwork: